//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.example.mvcsample;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.support.v4.app.Fragment;

public final class ControlerService_
    extends ControlerService
{


    public static ControlerService_.IntentBuilder_ intent(Context context) {
        return new ControlerService_.IntentBuilder_(context);
    }

    public static ControlerService_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ControlerService_.IntentBuilder_(supportFragment);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ControlerService_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ControlerService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ControlerService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
